### ISSUE TITLE
Set up GitHub action to run ESLint on PRs

### ISSUE THREAD

**Issue by audreyfeldroy** [margaritahumanitarian/helpafamily#163]
I believe ESLint runs as part of the build on Vercel, which isn't viewable to contributors unless we add them to the Vercel team at $20/user.

It would be nice to add a GitHub action that runs ESLint separate from the Vercel build, so that:
- contributors can see the ESLint build log
- ESLint failures block the Vercel deploy preview

**Comment by vincentrohde** [comment]
@audreyfeldroy If you don't mind I would love to implement this 👍

**Comment by RedFox0x20** [comment]
Hi @vincentrohde thanks for your interest, please feel free to implement the above and submit a PR, there is currently the `.github/workflows/format.yml` action that handles some of this but it may be the case that it is not setup correctly to handle new PRs. I have assigned this issue to you.

**Comment by audreyfeldroy** [comment]
Hey, thanks @vincentrohde for offering to help, and thank you @RedFox0x20 for providing starting guidance. We could definitely use help here.

Here's some further guidance to help you with this issue @vincentrohde...

Currently the GitHub action runs only on pushes to main, see lines 3-4:
https://github.com/margaritahumanitarian/helpafamily/blob/main/.github/workflows/format.yml#L3-L4

@marekrozmus tried to set up the Prettier GitHub action to run on PRs, but for some reason it would only run on PRs from the main repo, not from forks. See [his Prettier PR history](https://github.com/margaritahumanitarian/helpafamily/pulls?q=is%3Apr+prettier) for his past work.

#171 is an example of a PR where the submitter doesn't have access to the Vercel build log (`yarn run build`).

Looking at `package.json`, that runs `next build`: https://nextjs.org/docs/api-reference/cli#build
That appears to include running `next lint` based on the build log, though it's not clear exactly how from the Next.js docs on `next build`.

**Comment by vincentrohde** [comment]
Hey @audreyfeldroy I think I found a good solution for the issue, regarding blocking the Vercel deploy preview, if ESLint fails. It only requires a small change in the settings of the [Vercel app](https://github.com/apps/vercel). 

If you go to your https://vercel.com/{{ your team }}/helpafamily/settings page and change the `Build Command` setting to:

<img width="1433" alt="vercel-settings" src="https://user-images.githubusercontent.com/25182140/132404412-90c469e1-b1f9-48b1-84c8-9d5139146ebd.png">

```
eslint . --fix && npm run build
```

This also gave me access to the ESLint logs in my fork's Pull Requests. I set up a Vercel application for my fork, but it should be the same for Pull Requests in this repo, since it also has the Vercel bot reacting to Pushes on PRs.

**The output for ESLint fail in my [Pull Request](https://github.com/vincentrohde/helpafamily/pull/1)**

<img width="1612" alt="pull-request-error" src="https://user-images.githubusercontent.com/25182140/132405760-47081781-6837-4fc2-b937-1c9f934fb156.png">

If the user/dev clicks on the **"Preview"** option, it allows you to view the build log.

**This is the [latest build log](https://vercel.com/vincenzo/helpafamily/HvvK5BaqK9sP5DJJ4JUJWoFwdaeB)**

<img width="1433" alt="build-log" src="https://user-images.githubusercontent.com/25182140/132406036-71493302-4d31-4ef1-b46b-ef376fa40fe7.png">

**Comment by vincentrohde** [comment]
Thank you @audreyfeldroy for making me aware of this fork PR issue. I currently have a basic ESLint action setup that allows the user to see the ESLint logs.

I found a way to run ESLint when Vercel tries to deploy. This will block the deploy preview until the first commit is pushed, that successfully runs ESLint. It is fairly easy to setup. In your Vercel project settings you just have to update the `Build Command` to

<img width="1433" alt="vercel-settings" src="https://user-images.githubusercontent.com/25182140/132409841-5370956c-578b-475a-823b-cdd49ef04998.png">

```
eslint . --fix && npm run build
```

The result you will see in the [Pull Request](https://github.com/vincentrohde/helpafamily/pull/1)

<img width="1612" alt="pull-request-error" src="https://user-images.githubusercontent.com/25182140/132410261-3caa1f9f-d580-4ce4-82b6-9e3c6fb5e4ef.png">


Maybe this can be used in combination with displaying ESLint logs in a separate action? Then the dev knows that deploy failed, and will also see the logs for ESLint.

Regarding the fork issue, do you think it would be an option for the devs to create their own branches in the original repo (this one here) and open PRs towards main? I am not too familiar with this, but couldn't you make `main` a "protected branch" to prevent merges/ pushes without approval by the code owner(s)?

Anyway, I will try to find a way to run the actions even if they come from a fork 👍

**Comment by audreyfeldroy** [comment]
Wow, thank you @vincentrohde for exploring this and providing so much detail!

I've sent you an invite to our Vercel team so you can experiment there if you'd like. 

Your solution of running `eslint . --fix && npm run build` on Vercel is very creative! (Side note, for us it would be `yarn build`) I feel a bit funny about running `eslint . --fix` on the deploy previews, but it is a possible solution if we can't run it as an auto-added commit to all PRs.

That's an interesting idea about protecting `main` with CODEOWNERS and allowing contributors to work from branches in the repo. I think that could work really well for active contributors, alleviating at least part of the problem. Let's see if we can find a general case solution first, though 🙂 

Reading https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks#about-workflow-runs-from-public-forks I see that there's a setting to allow maintainers to approve workflow runs. I'll look for it.

**Comment by audreyfeldroy** [comment]
Here are the Actions settings on the repo:

![01 Actions permissions](https://user-images.githubusercontent.com/74739/132851939-a74b304a-0036-46cf-8d82-23b2aadc40a1.png)
![02 Runners](https://user-images.githubusercontent.com/74739/132851948-c7f43381-8474-43a4-afd7-1f624fc46b43.png)

**Comment by audreyfeldroy** [comment]
It looks like this is already set:

> Fork pull request workflows from outside collaborators
> Choose which subset of outside collaborators will require approval to run workflows on their pull requests. Learn more.
> - Require approval for first-time contributors: Only first-time contributors will require approval to run workflows.

**Comment by vincentrohde** [comment]
Hey @audreyfeldroy, from what I have seen, the issue with fork PRs not being able to run actions, seems to be built deliberately by Github.

_This is a mitigation against the possibility that a bad actor could open PRs against your repo and do things like list out secrets or just run up a large bill (once we start charging) on your account._

https://github.community/t/run-a-github-action-on-pull-request-for-pr-opened-from-a-forked-repo/16054/2

In the thread above I found a solution, that would allow you to bypass this built in security feature. It checks out the fork and then you are able to run ESLint on the fork code. I already tested this and it works. It shows the action's logs, so both the dev and the reviewer will be able to see the ESLint results.

```
name: ESLint for PR from Fork

on: [ pull_request_target ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: PR head repo
        id: head_repo_name
        run: |
          HEAD_REPO_NAME=$(jq -r '.pull_request.head.repo.full_name' "$GITHUB_EVENT_PATH")
          echo "PR head repo: $HEAD_REPO_NAME"
          echo "::set-output name=repo::$HEAD_REPO_NAME"
      - name: Checkout git repo
        uses: actions/checkout@v2
        with:
          repository: ${{ steps.head_repo_name.outputs.repo }}
          fetch-depth: 0
      - name: Install modules
        run: yarn install
      - name: Run ESLint
        run: yarn run eslint . --fix
```

**However, I would strongly advise against using this code, since it will leave your repo open to attacks**. This article here explains the issues a bit better.

_They may submit malicious changes to the existing build scripts like make or powershell files or redefine the build script in the package.json file. They can simply write their payload as a new test that will be run with others. They can achieve code execution even before the actual build happens. Npm packages for example may have custom preinstall and postinstall scripts, so running npm install would already trigger any malicious code if the attackers added a new package reference. Any modern build orchestration is complex enough to have multiple code injection points._

https://securitylab.github.com/research/github-actions-preventing-pwn-requests/

**Comment by vincentrohde** [comment]
@audreyfeldroy Does it work with the approval of workflows on forks? It seems this whole fork+workflows thing is still not really implemented by Github/ Microsoft at the moment. I think the approval option would be great, so the reviewer can check the changes for suspicious code first. Blindly running foreign code without any check seems too risky to be honest.

Ideally, the reviewer could check the code first for functionality and then before approving a merge. When everything seems good, the code could be auto checked by ESLint to make sure it follows the coding standards

**Comment by RedFox0x20** [comment]
@vincentrohde Thanks for providing some more info into this! 

@audreyfeldroy From what Vincent has provided here it would suggest to me that the best course of action would be to get the users to perform linting where necessary and provide assistance where they are unable to do so. I will take another look at the `PULL_REQUEST_TEMPLATE` feature of GitHub and attempt to get it working correctly with the repo to bring more attention to the requirement when a PR is produced.

**Comment by marekrozmus** [comment]
@vincentrohde I dig to the same stuff when trying to set up action for prettier. My guess is that the best solution would be to add `husky` and `lint-staged` and do that linting stuff before code is pushed to repository.

**Comment by vincentrohde** [comment]
@marekrozmus I think you're right. At my work the linting is also handled via Git hooks. 
@audreyfeldroy @RedFox0x20 If you don't mind I would be happy to implement a solution that uses hooks for linting 👍

**Comment by RedFox0x20** [comment]
@vincentrohde I like the idea of git hooks, not sure how portable they are though? Do they apply to the repository and get shared through? I've never really used them before, but I have seen similar things in use before so definitely could be a suitable option if easily applied to forks etc.
