### ISSUE TITLE
"Anyone in Need" form user experience

### ISSUE THREAD

**Issue by audreyfeldroy** [margaritahumanitarian/helpafamily#45]
This issue is particularly newbie-friendly and would help us a lot:

- [ ] In MainDonationForm.js, add a checkbox called "Anyone in Need"
- [ ] Click through to make sure it works

**Comment by ckkeppler** [comment]
I would like to handle this issue

**Comment by audreyfeldroy** [comment]
Hi @ckkeppler, thanks for offering to take this one. It looks like pull request #46 already implemented this as a toggle, but would you be interested on iterating on it further?

For example, if you can think of any ways to make the user experience of the "Anyone in need" toggle/checkbox form better, a PR would be wonderful.

**Comment by RedFox0x20** [comment]
A couple ways I think this form could be improved further may be to:
- Allow the user to select one of the `disabled` options, this would have to be rigged up so that the `Anyone in need` option is unchecked when one of the other options enabled. 
- Some slight indenting on other options to suggest a hierarchy which shows the relationship between the elements (you often see this done in similar situations)
- Ensuring all states have a clean desirable result, i.e. when a selection has been made and the `Anyone in need` option is selected after, we get a scenario where the donate message may be `Help Anyone in need, People of Color in Need, Immigrants in Need` which is messy and unnecessary. 

I am happy to leave this to others to have a go at as this is not my speciality, however will happily come back with tweaks.

**Comment by audreyfeldroy** [comment]
@RedFox0x20 Thanks for posting your form improvement ideas. I particularly like this one:

> Allow the user to select one of the disabled options, this would have to be rigged up so that the Anyone in need option is unchecked when one of the other options enabled.

@ckkeppler Would you like to try implementing this? You're also welcome to claim any other unclaimed issue and leave this one to someone else. No pressure 🙂

**Comment by audreyfeldroy** [comment]
Oh wow, I see you submitted a PR for this @rathijitpapon. I'll mark this issue as assigned to you then. Thank you so much for that.

@ckkeppler sorry about the confusion, I'm still getting used to how GitHub issue assignment works and should have assigned it to you when you commented. If your schedule permits, take a look at the other issues for anything else that interests you...your help with anything else would be appreciated very much.

**Comment by audreyfeldroy** [comment]
This is done and merged. I learned some really cool things from your PR @rathijitpapon, thank you! And thank you @RedFox0x20 for all the reviewing help.
