### ISSUE TITLE
We need to decide if use yarn or npm

### ISSUE THREAD

**Issue by marekrozmus** [margaritahumanitarian/helpafamily#70]
@audreyfeldroy I see that package-lock.json was added. This might introduce problems as we should have yarn.lock or package-lock.json. Otherwise we will go out of sync on those lock files and they will be useless.

**Comment by RedFox0x20** [comment]
`package-lock.json` was added in #61 by @GrungeKarma

From my understanding the project was started with using yarn, the best option may be to remove `package-lock.json` and adding it to the `.gitignore` file so if someone does use npm on their local repository, the changes don't interact with others using yarn. Ideally everyone would use the same tools but sometimes that doesn't happen.

I don't believe there would be any other issues caused by this solution?

**Comment by marekrozmus** [comment]
I agree with your proposal 🙂.
Although the locks are not used by developers it might be that some tools will get confused which lock file should be used and we will have some weird bugs.

**Comment by audreyfeldroy** [comment]
Good catch, I missed that in my earlier review. Hey @GrungeKarma, sorry about that, I should have reviewed more carefully or gitignored the file in the first place.

I think the Next.js world prefers yarn these days? I'm good with .gitignoring `package-lock.json` if anyone wants to send a quick PR for it.

**Comment by RedFox0x20** [comment]
Ok, I can do that.
